services:
  symfony:
    build:
      context: .
      dockerfile: docker/local/symfony/Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: php -S 0.0.0.0:8000 -t public

  postgres:
    image: postgres:16
    container_name: symfony_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
