services:
  symfony:
    build:
      context: .
      dockerfile: docker/local/symfony/Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app:z
    depends_on:
      - postgres
    command: php -S 0.0.0.0:8000 -t public

  postgres:
    image: postgres:17
    container_name: symfony_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  frontend:
    build:
      context: .
      dockerfile: docker/local/vite/Dockerfile
    container_name: vue_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app:z
    command: sh -c "pnpm install && pnpm dev"
    depends_on:
      - symfony

volumes:
  db_data:
